name: testing
on:
  push:
    branches:
      main
permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  tesingjob:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.2
    - name: install node modules and build in UI
      working-directory: .\vite-project   
      run: npm i && npm run build
    - name: install node modules in server
      working-directory: .\server   
      run: npm i && npm start
    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v1.0.8
      with:
        path: "./vite-project/dist"
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v2.0.1
      
      
    
  
